language: perl
sudo: false

cache:
  directories:
      - $HOME/perl5/perlbrew/perls/$TRAVIS_PERL_VERSION/lib/site_perl/
      - $HOME/perl5/perlbrew/perls/$TRAVIS_PERL_VERSION/bin/

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install:
  - cpanm --quiet --notest --installdeps .

script:
  - prove -lr t/
